version: '3.9'
services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    env_file:
      - "compose.env"
    depends_on:
      - "db"
      - "cache"
  db:
    image: "mysql:8"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - type: "bind"
        source: "./db/conf.d"
        target: "/etc/mysql/conf.d"
      - type: "bind"
        source: "./db/docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"
  cache:
    user: "0:0"
    image: "redis:7"
    ports:  
      - "6379:6379"